### ISSUE TITLE
make wouldn't work

### ISSUE THREAD

**Issue by yangya** [blackrim/phlawd_db_maker#2]
I followed the instruction to use sqlitewrapper and copy it over but still get this:

[ 25%] Building CXX object CMakeFiles/phlawd_db_maker.dir/src/utils.cpp.o
/home/yayang/apps/phlawd_db_maker/src/utils.cpp:132:42: warning: unknown escape sequence: '\.'
      if(*(string(dirp->d_name).begin())=='\.')
                                          ^
/home/yayang/apps/phlawd_db_maker/src/utils.cpp: In function ‘int getdir(std::string, std::vector<std::basic_string<char> >&)’:
/home/yayang/apps/phlawd_db_maker/src/utils.cpp:123:29: error: ‘errno’ was not declared in this scope
         cout << "Error(" << errno << ") opening " << dir << endl;
                             ^
CMakeFiles/phlawd_db_maker.dir/build.make:123: recipe for target 'CMakeFiles/phlawd_db_maker.dir/src/utils.cpp.o' failed
make[2]: *** [CMakeFiles/phlawd_db_maker.dir/src/utils.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/phlawd_db_maker.dir/all' failed
make[1]: *** [CMakeFiles/phlawd_db_maker.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2

Some version issue perhaps?

**Comment by blackrim** [comment]
you need to do cmake . first and then make
